@echo off
setlocal

SET VER_MAJOR=1
SET VER_MINOR=6

FOR /F "TOKENS=1,2 eol=/ DELIMS=/ " %%A IN ('DATE/T') DO SET mm=%%A
FOR /F "TOKENS=1,2 DELIMS=/ eol=/" %%A IN ('DATE/T') DO SET dd=%%B
FOR /F "TOKENS=2,3 DELIMS=/ " %%A IN ('DATE/T') DO SET yyyy=%%B

SET VER_BUILD=%date:~10,4%%date:~7,2%%date:~4,2%
SET VER_FILE="%1"

if %VER_FILE% == "" SET VER_FILE="./version.h"

echo Version: %VER_MAJOR%.%VER_MINOR%.%VER_BUILD%

echo #ifndef  __NRD_VERSION_CONTROL_HEADER_AUTOGENERATED_H__ > "%VER_FILE%" 
echo #define  __NRD_VERSION_CONTROL_HEADER_AUTOGENERATED_H__ >> "%VER_FILE%" 
echo static const int VERSION_NUMBER_MAJOR=%VER_MAJOR%; >> "%VER_FILE%" 
echo static const int VERSION_NUMBER_MINOR=%VER_MINOR%; >> "%VER_FILE%" 
echo static const int VERSION_NUMBER_BUILD=%VER_BUILD%; >> "%VER_FILE%" 
echo #endif >> "%VER_FILE%" 

@endlocal
@echo on

