#!/bin/sh
##
# Installs NuoRDS Proxy
#
##

if [ $UID -ne 0 ] ; then
   echo   "error: NOT super-user."
   exit 1
fi

if [ ! -f "./nrdproxy_service" ] || \
   [ ! -f "./com.nuords.nrdproxyd.plist" ] || \
   [ ! -f "./nrdproxyd.cfg.sample" ] || \
   [ ! -f "./nrdproxyd.cfg.simple" ] || \
   [ ! -f "./nrdproxyd" ] ; then
   echo   "fault: Source directory does not contain a package."
   exit 1
fi

perm_set_rwx()
{
  xattr -cr "$1"
  chmod u=rwx,g=rx,o=rx "$1"
  chown root "$1" 
  return $?
}

perm_set_rw()
{
  xattr -cr "$1"
  chmod u=rw,g=r,o=r "$1"
  chown root "$1" 
  return $?
}

echo   "Installing NuoRDS Proxy..."

#Install binaries

if [ ! -d "/usr/local/bin" ] ; then mkdir -p "/usr/local/bin" ; fi

cp "./nrdproxy_service"  "/usr/local/bin/"
cp "./nrdproxyd"  "/usr/local/bin/"

if [ "$?" != "0" ] ; then
   echo   "fault: Could not copy binaries."
   exit 1
fi 
 
perm_set_rwx "/usr/local/bin/nrdproxy_service"
perm_set_rwx "/usr/local/bin/nrdproxyd" 

#Setup the daemon

if [ ! -d "/Library/LaunchDaemons" ] ; then mkdir -p "/Library/LaunchDaemons" ; fi
cp "./com.nuords.nrdproxyd.plist" "/Library/LaunchDaemons/"
if [ "$?" != "0" ] ; then
   echo   "fault: Could not configure daemon."
   exit 1
fi 
perm_set_rw "/Library/LaunchDaemons/com.nuords.nrdproxyd.plist"

#Install config sample

if [ ! -d "/etc/nuords" ] ; then mkdir -p "/etc/nuords" ; fi

cp "./nrdproxyd.cfg.sample" "/etc/nuords/"
cp "./nrdproxyd.cfg.simple" "/etc/nuords/"

if [ "$?" != "0" ] ; then
   echo "fault: Could not copy configuration samples."
   exit 1
fi 

perm_set_rw "/etc/nuords/nrdproxyd.cfg.sample"
perm_set_rw "/etc/nuords/nrdproxyd.cfg.simple"

echo "Done."

if [ ! -f "/etc/nuords/nrdproxyd.cfg" ] ; then
   echo "Do not forget to create \"/etc/nuords/nrdproxyd.cfg\""
   echo "Configuration sample 1: \"/etc/nuords/nrdproxyd.cfg.simple\""
   echo "Configuration sample 2: \"/etc/nuords/nrdproxyd.cfg.sample\"" 
fi

exit 0
