#!/bin/sh
##
# NuoRDS Proxy Server control
# Mac OS X 10.12+
#
##

if [ $UID -ne 0 ] ; then
   echo   "ERROR: You have not permissions to manage NuoRDS Proxy Server."
   echo   "Please use \"sudo\", e.g: sudo nrdproxyctl start -w"
   exit 1
fi

CMD="$1"
OPT="$2"

if [ "$OPT" = "" ] ; then OPT="-F" ; fi

if [ "$CMD" = "start" ] ;  then

   launchctl load $OPT "/Library/LaunchDaemons/com.nuords.nrdproxyd.plist"

elif [ "$CMD" = "stop" ] ;  then

   launchctl unload $OPT "/Library/LaunchDaemons/com.nuords.nrdproxyd.plist" > /dev/null 2>&1

elif [ "$CMD" = "restart" ] ; then

   launchctl unload $OPT "/Library/LaunchDaemons/com.nuords.nrdproxyd.plist" > /dev/null 2>&1
   launchctl load $OPT "/Library/LaunchDaemons/com.nuords.nrdproxyd.plist"
   
elif [ "$CMD" = "state" ] ;  then

   launchctl list | grep com.nuords.nrdproxyd

else
   echo   "ERROR: Unknown command: $CMD"
   echo   "USAGE: nrdproxyctl start/stop/state [-w]"
   echo   "NOTE:  Use -w option to store state permanently"
   exit 1 
fi

exit $?
