#!/bin/sh

VER_MAJOR=1
VER_MINOR=6
VER_BUILD=`date "+%Y%m%d"`
VER_FILE="$1"

if [ "$VER_FILE" = "" ] ; then
  VER_FILE=version.h
fi

echo "Version: "$VER_MAJOR.$VER_MINOR.$VER_BUILD

echo "#ifndef  __NRD_VERSION_CONTROL_HEADER_AUTOGENERATED_H__" > "$VER_FILE" 
echo "#define  __NRD_VERSION_CONTROL_HEADER_AUTOGENERATED_H__" >> "$VER_FILE" 
echo "static const int VERSION_NUMBER_MAJOR=$VER_MAJOR;" >> "$VER_FILE"
echo "static const int VERSION_NUMBER_MINOR=$VER_MINOR;" >> "$VER_FILE"
echo "static const int VERSION_NUMBER_BUILD=$VER_BUILD;" >> "$VER_FILE"
echo "#endif" >> "$VER_FILE"

