# ********************************************************************
# Project : NuoRDS Proxy
# 
# ********************************************************************
# Description :  Makefile for NuoRDS Proxy (Linux). 
# 
# ********************************************************************

#Config

#BLD_DEST:=x86-64
#BLD_OPTS:=-march=$(BLD_DEST)

ifeq ($(OS_NAME),)
	OS_NAME:=linux
endif

#Includes
include ../unix/makefile
