# ********************************************************************
# Project : NuoRDS Proxy
# 
# ********************************************************************
# Description :  Makefile for NuoRDS Proxy (Linux). 
# 
# ********************************************************************

#Config

ifeq ($(BLD_DEST),)
	BLD_DEST:=linux
endif

#Includes
include ../unix/makefile
