# ********************************************************************
# Project : NuoRDS Proxy
# 
# ********************************************************************
# Description :  Makefile for NuoRDS Proxy (Linux). 
# 
# ********************************************************************

#Config
ifeq ($(OS_SYS),)
	OS_SYS:=linux
endif

#Includes
include ../unix/makefile
